language: ruby
rvm:
  - 2.2.2
  - 2.3.0

addons:
  apt:
    packages:
      vim-nox

before_install:
  - gem install bundler

gemfile:
  - ./gemfiles/Gemfile.chef.11.18.12
  - ./gemfiles/Gemfile.chef.12.16.42
